# docker-compose.yml
# Este archivo va en la RAÍZ de tu proyecto (mismo nivel que pom.xml)

version: '3.8'

services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_DB: medical_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hospital-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medical_system"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio de la API Spring Boot
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hospital-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/medical_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - hospital-network

volumes:
  postgres_data:
    driver: local

networks:
  hospital-network:
    driver: bridge